import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import vm from 'node:vm';import {load} from 'cheerio';
const ROOT=path.resolve(import.meta.dirname,'..'),OUT=path.join(ROOT,'public');
vm.runInThisContext(fs.readFileSync(path.join(ROOT,'assets/lab-math.js'),'utf8'));const M=globalThis.SGMath;
for(const preset of ['original','trail','cycle']){const edges=M.edgesFor(preset),info=M.analyze(edges);assert.equal(info.connected,true);assert.equal(info.odd.length,{original:4,trail:2,cycle:0}[preset]);const solution=M.euler(edges);if(preset==='original')assert.equal(solution,null);else{assert.equal(solution.edges.length,edges.length);assert.equal(new Set(solution.edges).size,edges.length);solution.edges.forEach((id,i)=>{const e=edges.find(x=>x.id===id),from=solution.vertices[i],to=solution.vertices[i+1];assert.ok((e.u===from&&e.v===to)||(e.v===from&&e.u===to))});if(preset==='cycle')assert.equal(solution.vertices[0],solution.vertices.at(-1));else assert.notEqual(solution.vertices[0],solution.vertices.at(-1))}}
assert.equal(M.analyze([{id:'x',u:'A',v:'B'},{id:'y',u:'C',v:'D'}]).possible,false);
const disconnectedCycles=[['x1','A','B'],['x2','B','C'],['x3','C','A'],['y1','D','E'],['y2','E','F'],['y3','F','D']].map(([id,u,v])=>({id,u,v}));assert.equal(M.analyze(disconnectedCycles).odd.length,0);assert.equal(M.analyze(disconnectedCycles).connected,false);assert.equal(M.euler(disconnectedCycles),null);assert.equal(M.euler([{id:'x',u:'A',v:'B'},{id:'y',u:'C',v:'D'}]),null);
for(const knows of [true,false])for(const entry of [0,1])for(const challenge of [0,1])assert.equal(M.success(knows,entry,challenge),knows||entry===challenge);
for(let n=1;n<=20;n++)assert.equal(M.probability(n),1/(2**n));
function files(dir){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?files(path.join(dir,e.name)):[path.join(dir,e.name)])}
const htmlFiles=files(OUT).filter(f=>f.endsWith('.html'));let checkedLinks=0;const errors=[];
const ids=html=>new Set([...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]));
for(const file of htmlFiles){const html=fs.readFileSync(file,'utf8'),allIds=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);if(new Set(allIds).size!==allIds.length)errors.push(file+': duplicate IDs');assert.match(html,/<html lang="(?:es|en)"/);if(file.includes('/en/'))assert.match(html,/<html lang="en"/);const ownIds=ids(html);
for(const m of html.matchAll(/\b(?:href|src)="([^"]+)"/g)){const u=m[1].replaceAll('&amp;','&');if(/^(?:https?:|data:|mailto:)/.test(u))continue;checkedLinks++;if(u==='#'){errors.push(file+': placeholder link');continue}const [base,fragment]=u.split('#'),pathname=decodeURIComponent(base.split('?')[0]);let target=pathname?(pathname.startsWith('/')?path.join(OUT,pathname):path.resolve(path.dirname(file),pathname)):file;if(fs.existsSync(target)&&fs.statSync(target).isDirectory())target=path.join(target,'index.html');const legacy=path.basename(target)==='konigsberg_dfs_2.html';if(!fs.existsSync(target)&&!legacy)errors.push(file+': missing '+u);else if(fragment&&!legacy&&target.endsWith('.html')&&fs.existsSync(target)){const targetIds=target===file?ownIds:ids(fs.readFileSync(target,'utf8'));if(!targetIds.has(decodeURIComponent(fragment)))errors.push(file+': missing anchor '+u)}}
}
const catalog=JSON.parse(fs.readFileSync(path.join(OUT,'assets/catalog.json')));assert.equal(catalog.length,32);assert.ok(catalog.every(e=>e.englishComplete));
const searchIndex=JSON.parse(fs.readFileSync(path.join(OUT,'assets/search-index.json')));assert.equal(searchIndex.length,32);assert.ok(searchIndex.every(e=>e.es.length>1200&&e.en.length>1200),'Both language bodies must be complete');
for(const e of catalog){const file=path.join(OUT,'en/articles',e.id,'index.html'),$=load(fs.readFileSync(file,'utf8'));assert.ok($('.prose').text().length>1500,e.id+': complete English article');assert.equal($('h1').length,1,e.id+': one page title');const schema=JSON.parse($('script[type="application/ld+json"]').text());assert.equal(schema.inLanguage,'en');assert.equal(schema['@type'],'Article')}
const math=JSON.parse(fs.readFileSync(path.join(OUT,'assets/math-report.json')));assert.equal(math.errors.length,0);assert.ok(math.rendered>=4);for(const lang of ['es','en']){const $=load(fs.readFileSync(path.join(OUT,lang,lang==='es'?'articulos':'articles','tiktok/index.html'),'utf8'));assert.ok($('.katex-display').length>0,'TikTok display equation');assert.ok($('math').length>0,'Accessible MathML')}
assert.ok(!fs.readFileSync(path.join(OUT,'index.html'),'utf8').includes('api.github.com'));
if(errors.length){console.error(errors.join('\n'));process.exitCode=1}else console.log(JSON.stringify({result:'PASS',htmlPages:htmlFiles.length,internalLinks:checkedLinks,mathScenarios:'Euler original/trail/cycle/disconnected + 8 ZKP combinations + n=1..20'}));
