import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
import {Window} from 'happy-dom';
const root=path.resolve(import.meta.dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
const js=read('assets/site.js'),index=JSON.parse(read('public/assets/search-index.json'));
function page(file,url='https://sgevatschnaider.github.io/es/',state={}){const w=new Window({url,settings:{disableCSSFileLoading:true,disableJavaScriptFileLoading:true,enableJavaScriptEvaluation:true,suppressInsecureJavaScriptEnvironmentWarning:true}});w.fetch=async()=>({ok:true,json:async()=>index});for(const [key,value]of Object.entries(state))w.localStorage.setItem(key,JSON.stringify(value));w.document.write(read(file));w.eval(js);return w}
const wait=()=>new Promise(r=>setTimeout(r,30));
const w=page('public/es/index.html');
assert.equal(w.document.querySelectorAll('[data-catalog] [data-article]:not([hidden])').length,9);
w.document.querySelector('[data-more]').click();assert.equal(w.document.querySelectorAll('[data-catalog] [data-article]:not([hidden])').length,18);
const query=w.document.querySelector('[data-search]');query.value='spectral';query.dispatchEvent(new w.Event('input'));await wait();assert.ok(w.document.querySelector('[data-catalog] [data-article="expander"]:not([hidden])'),'Search must find an English body term from Spanish home');assert.ok(w.document.querySelector('[data-article="expander"] [data-excerpt]').textContent.toLowerCase().includes('spectral'));
assert.ok(w.document.querySelector('[data-language-link]').href.includes('q=spectral'));
w.document.querySelector('[data-reset-filters]').click();const save=w.document.querySelector('[data-catalog] [data-save]');save.click();const availability=w.document.querySelector('[data-availability]');availability.value='saved';availability.dispatchEvent(new w.Event('change'));assert.equal(w.document.querySelectorAll('[data-catalog] [data-article]:not([hidden])').length,1);assert.equal(JSON.parse(w.localStorage.getItem('sg-favorites')).length,1);
const route=w.document.querySelector('[data-route-step]');route.click();assert.ok(w.document.querySelector('[data-route-status]').textContent.startsWith('1 de 4'));
const english=page('public/en/index.html','https://sgevatschnaider.github.io/en/',{'sg-route-steps':JSON.parse(w.localStorage.getItem('sg-route-steps'))});assert.ok(english.document.querySelector('[data-route-step]').checked);assert.ok(english.document.querySelector('[data-route-status]').textContent.startsWith('1 of 4'));
const article=page('public/en/articles/expander/index.html','https://sgevatschnaider.github.io/en/articles/expander/');assert.ok(article.document.querySelector('.prose').textContent.length>10000);article.document.querySelector('[data-read-complete]').click();assert.equal(article.document.querySelector('[data-read-complete]').getAttribute('aria-pressed'),'true');const note=article.document.querySelector('[data-reading-note]');note.value='My idea about expansion';note.dispatchEvent(new article.Event('input'));assert.equal(JSON.parse(article.localStorage.getItem('sg-reading')).expander.note,note.value);for(let i=0;i<8;i++)article.document.querySelector('[data-font-size=larger]').click();assert.equal(article.document.documentElement.style.getPropertyValue('--reading-scale'),'1.3');const reread=page('public/es/articulos/expander/index.html','https://sgevatschnaider.github.io/es/articulos/expander/',{'sg-reading':JSON.parse(article.localStorage.getItem('sg-reading'))});assert.equal(reread.document.querySelector('[data-reading-note]').value,note.value);assert.equal(reread.document.querySelector('[data-read-complete]').getAttribute('aria-pressed'),'true');
const unread=page('public/en/index.html','https://sgevatschnaider.github.io/en/?show=unread',{'sg-reading':JSON.parse(article.localStorage.getItem('sg-reading'))});assert.equal(unread.document.querySelector('[data-article=expander]').hidden,true);
const lab=page('public/es/simulaciones/zkp/index.html','https://sgevatschnaider.github.io/es/simulaciones/zkp/');lab.eval(read('assets/lab-math.js'));lab.eval(read('assets/zkp.js'));assert.match(lab.document.querySelector('#stage-indicator').textContent,/Preparado/);for(let i=0;i<4;i++)lab.document.querySelector('#step').click();assert.equal(lab.document.querySelector('#rounds').textContent,'1');assert.equal(lab.document.querySelector('#passed').textContent,'1');assert.match(lab.document.querySelector('#stage-indicator').textContent,/Paso 4/);lab.document.querySelector('#reset').click();assert.equal(lab.document.querySelector('#rounds').textContent,'0');lab.document.querySelector('#theory-rounds').value='10';lab.document.querySelector('#theory-rounds').dispatchEvent(new lab.Event('input'));assert.match(lab.document.querySelector('#theory-prob').textContent,/0,0976563%/);lab.document.querySelector('#montecarlo').click();assert.match(lab.document.querySelector('#mc-result').textContent,/probabilidad cero/);for(const f of lab.document.querySelectorAll('[data-challenge]')){f.querySelector(`[value="${f.dataset.correct}"]`).click();f.querySelector('button').click();assert.equal(f.dataset.result,'correct')}
lab.document.querySelector('#hash-secret').value='my secret';lab.document.querySelector('#commit').click();await wait();assert.match(lab.document.querySelector('#hash-result').textContent,/SHA-256: [a-f0-9]{64}/);lab.document.querySelector('#hash-reveal').value='my secret';lab.document.querySelector('#reveal').click();await wait();assert.match(lab.document.querySelector('#hash-result').textContent,/Verificación correcta/);lab.document.querySelector('#hash-reveal').value='wrong';lab.document.querySelector('#reveal').click();await wait();assert.match(lab.document.querySelector('#hash-result').textContent,/no coincide/);
const enLab=page('public/en/simulations/zkp/index.html','https://sgevatschnaider.github.io/en/simulations/zkp/');enLab.eval(read('assets/lab-math.js'));enLab.eval(read('assets/zkp.js'));assert.match(enLab.document.querySelector('#stage-indicator').textContent,/Ready/);enLab.document.querySelector('#step').click();assert.match(enLab.document.querySelector('#stage-indicator').textContent,/Step 1/);
const corrupt=page('public/en/index.html','https://sgevatschnaider.github.io/en/',{'sg-reading':[], 'sg-favorites':{},'sg-route-steps':null,'sg-font-scale':'bad'});assert.ok(corrupt.document.querySelector('[data-results]').textContent.includes('9 of 32'));
for(const window of [w,english,article,reread,unread,lab,enLab,corrupt])window.happyDOM.abort();
console.log('PASS: full-text ES/EN search, excerpts, filters, saved/read state, pathways, shared notes, font limits, ZKP stages/probability/challenges and SHA-256 match/mismatch.');
